// constants/user.js
export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN';
export const SWITCH_ACCOUNT_ROLE = 'SWITCH_ACCOUNT_ROLE';
